### ISSUE TITLE
Why not working if i run eslint globaly ?

### ISSUE THREAD

**Issue by jt3k** [blond/eslint-config-pedant#1]
![img](https://i.imgur.com/YI3Pkls.png)

**Comment by jt3k** [comment]
oh. after I install globally eslint-config-pedant it work well

```
npm install eslint-config-pedant -g 
```

Can it be fixed without installing eslint-config-pedant globally ?

**Comment by blond** [comment]
@jt3k, thank you for your feedback!

This is correct behavior. Please take a look at [documentation](http://eslint.org/docs/user-guide/configuring#configuring-plugins) more specifically a note at the bottom.

**The similar issue:** https://github.com/eslint/eslint/issues/5626

I also added info about globally-installed instance of ESLint to readme: https://github.com/blond/eslint-config-pedant/pull/2
