### ISSUE TITLE
Remove comma-dangle rule for ES5

### ISSUE THREAD

**Issue by blond** [blond/eslint-config-pedant#14]
This rule is important only for `ES3`:

> This can cause problems with `IE6/7` and `IE9` if it's in quirksmode. Also, in some implementations of ES3 would add length to an array if it had an additional trailing comma. This was clarified in `ES5` (source):

This was clarified in `ES5` ([source](http://es5.github.io/#D)):

> Edition 5 clarifies the fact that a trailing comma at the end of an ArrayInitialiser does not add to the length of the array. This is not a semantic change from Edition 3 but some implementations may have previously misinterpreted this.

For `ES5` and `ES2015` this rule is more stylistic. For, example, you may want to use trailing commas to cleaner git diffs:

``` js
// bad - git diff without trailing comma
const hero = {
     firstName: 'Florence',
-    lastName: 'Nightingale'
+    lastName: 'Nightingale',
+    inventorOf: ['coxcomb graph', 'modern nursing']
};

// good - git diff with trailing comma
const hero = {
     firstName: 'Florence',
     lastName: 'Nightingale',
+    inventorOf: ['coxcomb chart', 'modern nursing'],
};
```

I don't want to `eslint-config-pedant` limit your choice of code style.

**Comment by blond** [comment]
@zxqfox, can we get `ecmaVersion` from `.eslintrc` in `eslint-config-pedant` package?

For example:

``` js
const ecmaVersion = require('eslint').getCurrentEcmaVersion();
const rules = {};

if (ecmaVersion === 3) {
    rules['comma-dangle'] = ['error', 'never'];
}

return rules;
```

**Comment by qfox** [comment]
@blond Something like

``` js
const EslintConfig = require('eslint/lib/config');
const eslintConfig = new EslintConfig({cwd: process.cwd()});
const conf = eslintConfig.getConfig();
Object(conf.parserOptions).ecmaVersion; // 3, 5, 6, 7 or undefined
```

**Comment by qfox** [comment]
Why you scared about trailing `,` at all? Everyone using uglify so no reason to check it differently for ES3.

**Comment by jt3k** [comment]
what about allow to set trailing-comma in the default pedant config (not for es3, es5)?
In es2015 trailing comma is ok and It does not result in an error
