### ISSUE TITLE
Settings to lint deps.js

### ISSUE THREAD

**Issue by tadatuta** [blond/eslint-config-pedant#28]
Please provide some info on how to lint `*.deps.js` files with `eslint-config-pedant` as a base.

**Comment by blond** [comment]
What's the problem?

**Comment by tadatuta** [comment]
Files like

```
({
     shouldDeps: 'blah'
})
```

is now considered as errors.

**Comment by blond** [comment]
I think that `pedant` should not support specific cases.

We can ignore `deps.js` files or configure ESLint to processed `deps.js` files with custom rules.

Also we can turn off `no-unused-expressions` rule in projects.

**Comment by tadatuta** [comment]
Can you please show an example of config to process `deps.js` files with custom rules?

**Comment by blond** [comment]
`.eslintrc`

``` yaml
extends: eslint-config-pedant
```

``` shell
$ eslint . --ignore-pattern="**/*.deps.js" && eslint --rule="no-unused-expressions: off"
```

**Comment by iamstarkov** [comment]
another way:

```
echo "**/*.deps.js" >> .eslintignore
```

> I think that pedant should not support specific cases.

👍

**Comment by iamstarkov** [comment]
issue might be considered closed, i think

**Comment by belozer** [comment]
In eslint has a branch deliberations in such situations.
https://github.com/eslint/eslint/issues/3611

**Comment by iamstarkov** [comment]
@belozer its accepted as an idea, but not landed in master, thus yet not released

**Comment by belozer** [comment]
@iamstarkov I know. But once the idea become a realization.
