### ISSUE TITLE
no-dupe-args  error in console

### ISSUE THREAD

**Issue by jt3k** [blond/eslint-config-pedant#29]
падает с такой ошибкой:

``` log
./app/scripts/app.js
Module build failed: Error: pedant:
    Configuration for rule "no-dupe-args" is invalid:
    Value "error" is the wrong type.
```

...Referenced from .eslintrc

запускаю линтер через вебпаковый лоадер eslint-loader
в конфиге вебпака это выглядит как добавление лоадера вот такой строкой:

```
{
  test: /\.js$/,
  loader: 'eslint-loader',
  exclude: /node_modules/
}
```

и добавлением в массив  плагинов вот этого 

```
eslint: {
    configFile: path.join(__dirname, '.eslintrc'),
    emitErrors: false,
    emitWarning: true,
    formatter: eslintFormatter({notify})
}
```

версии:

```
$ cat package.json | grep eslint 
    "lint:scripts": "eslint app gulp",
    "babel-eslint": "^4.1.5",
    "eslint": "^1.9.0",
    "eslint-config-pedant": "^0.3.0",
    "eslint-loader": "^1.1.1",
    "eslint-config-pedant": "^0.3.0"
```

.eslintrc

``` yaml
env:
  browser: true
  es6: true
extends: pedant
parserOptions:
  ecmaVersion: 7
  sourceType: module

```

---
- я попробовал удалять глобальный eslint и устанавливать заново 
  `npm install --save-dev eslint-config-pedant` 
  (перед этим убрав его из package.json) но это не помогло.
  После этого возникает та же ошибка :(
- также попробовал установить педант более старой версии:
  `npm install --save-dev eslint-config-pedant@0.1.1` 

тоже не помогло.

---

Сразу прошу прошения за многобукв и кажущуюся лень -- но я хз как на сайте eslint искать в какой версии еслинта у нас настройка "no-dupe-args" депрекейтнулась :(

---

Еси впадлу отвечать - свистни я закрою этот ишьюс

**Comment by qfox** [comment]
eslint надо обновить, 1.9 это древнючая версия.

p.s. Настройка не депрекейтнулась. проблема в "error". В старых версиях надо писать циферки.

А еще лучше обновить сам педант до последней версии и использовать `pedant/es6` вместо `pedant`

**Comment by jt3k** [comment]
@zxqfox хых. а за еслинтом надо ещё и eslint-loader апнуть  спасибо. щас проверю

**Comment by qfox** [comment]
@jt3k Да, всё так ;-) Протухло всё изрядно.

**Comment by jt3k** [comment]
ееее проканало!
![image](https://cloud.githubusercontent.com/assets/1261240/17531499/c69ea8e0-5e84-11e6-892e-43cb731785ac.png)
спасибо за поддержку!
